name: Workflow2
on:
  workflow_run:
    workflows: 
      - Workflow1
    types: 
      - completed

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Build Contents
        run: echo "HI"
