name: Workflow2
on:
  workflow_run:
    workflows: ["Workflow1"]
    types:
      - completed

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo "${{ github.event.workflow_run.conclusion }}"
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"
